# Generated by Django 4.2.4 on 2023-09-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio_de',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='bio_en',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='bio_uz',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='genre_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='genre_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='genre_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='about_book_de',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='about_book_en',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='about_book_uz',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='genre_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='genre_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='genre_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
