# Generated by Django 4.2.4 on 2023-09-04 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_author_bio_de_author_bio_en_author_bio_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.genre'),
        ),
        migrations.AlterField(
            model_name='author',
            name='genre_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.genre'),
        ),
        migrations.AlterField(
            model_name='author',
            name='genre_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.genre'),
        ),
        migrations.AlterField(
            model_name='author',
            name='genre_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.genre'),
        ),
    ]
