# Generated by Django 4.2.4 on 2023-09-04 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_genre_alter_author_genre_alter_author_genre_de_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genre',
            table='genre',
        ),
    ]
