# Generated by Django 4.2.4 on 2023-09-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_genre_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='author',
            name='genre_de',
        ),
        migrations.RemoveField(
            model_name='author',
            name='genre_en',
        ),
        migrations.RemoveField(
            model_name='author',
            name='genre_uz',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre_de',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre_uz',
        ),
        migrations.AddField(
            model_name='genre',
            name='type_genre_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='type_genre_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='type_genre_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
