# Generated by Django 4.2.4 on 2023-09-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_author_genre_book_genre_alter_author_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='about_book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='about_book_de',
        ),
        migrations.RemoveField(
            model_name='book',
            name='about_book_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='about_book_uz',
        ),
        migrations.AddField(
            model_name='book',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='bio_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='bio_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='bio_uz',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio_de',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio_uz',
            field=models.TextField(default='', null=True),
        ),
    ]
